### ISSUE TITLE
GrabCuts feature requests and notebook commentary

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#111]
* [x] Need to add the crs input to the grabcut dashboard in the example notebook (the tile sources in the last cell bring it in correctly, but the dashboard instantiation needs to have it included)  
  
* [x] Need to add to the notebook a demo on how to grab the data back out. Is `dashboard.result.array()` the best method?  
  
* Do we want to denote foreground and background as polygons or polylines? Personally, I think its easier and quicker as a user to click and drag. I don't think that's available, but I still think clicking a line would require less thought for a user. Opinions?    
    
* [x] Philipp mentioned setting min length/area for the resulting polygons/lines to clean up the image. That is definitely a desired feature. It also might be neat to see that as a slider.   
   
* [x] When I've used grabcuts before, there was a "number of iterations" option. I don't see access to that feature in the code. That's another option in addition to downsampling that helps speed up the calculation.

**Comment by kcpevey** [comment]
I will also just mention that in order to implement this in my workflows, the related feature requirements are  
* snapping (including path breaking)  
* paths as connected polylines  
* polygons as connected polylines  
  
We've discussed these a lot since the original issue was published in #38

**Comment by philippjfr** [comment]
>Need to add the crs input to the grabcut dashboard in the example notebook (the tile sources in the last cell bring it in correctly, but the dashboard instantiation needs to have it included)

Should be straightforward.

> Need to add to the notebook a demo on how to grab the data back out. Is dashboard.result.array() the best method?

``dashboard.result.array()``, ``dashboard.result.dframe()``, ``dashboard.result.split(datatype='array')`` or ``dashboard.result.geom()`` should all work. A user should choose whichever is most useful for further processing.

>Do we want to denote foreground and background as polygons or polylines?

Whether to use paths or polygons is configurable in the Dashboard constructor. If you'd prefer I'll switch to the line based version by default, although if we want to control the line width I'll probably have to implement an aggregation operation that supports it.

>Philipp mentioned setting min length/area for the resulting polygons/lines to clean up the image. That is definitely a desired feature. It also might be neat to see that as a slider.

Agreed, are you aware of any implementations that would work here? I suppose we could just try using shapely to compute the areas and then apply a filter that way.

>When I've used grabcuts before, there was a "number of iterations" option

That should be quite forward to expose.

**Comment by kcpevey** [comment]
>dashboard.result.array(), dashboard.result.dframe(), dashboard.result.split(datatype='array') or dashboard.result.geom() should all work. A user should choose whichever is most useful for further processing.  
  
The results appear to be one big array of points, each line separated by a NaN point. Is that correct?  
That answer is related to this answer:  

>are you aware of any implementations that would work here? I suppose we could just try using shapely to compute the areas and then apply a filter that way.  
  
Other software handles this by returning polygons, grabbing the image edges as needed. Everything returns as a closed polygon. That also means that the results are prepped for, say, filigree. The minimum threshold is handled by pixel (i think) area of the returned polygons. Which is good for clearing out tiny island features.   
  
If the earthsim implementation returns paths, I'd need the ability to finish clicking out the remainder of the polygon (required features mentioned above). That also would require us to set the minimum threshold on path length. Depending on how things come back from GrabCuts, that may not be appropriate (would I ever get a path that for some reason was broken into three conjoined pieces, with say, one short piece in the middle?). That would also have us running a distance calculation between every point, which won't be computationally efficient.   
  
All that said, if this implementation returns polygons, several things get easier or take care of themselves.   
  
It sounds like I've talked myself into an answer, but I'd like to hear other opinions.

**Comment by kcpevey** [comment]
>>Do we want to denote foreground and background as polygons or polylines?

>Whether to use paths or polygons is configurable in the Dashboard constructor. If you'd prefer I'll switch to the line based version by default, although if we want to control the line width I'll probably have to implement an aggregation operation that supports it.  
  
I'd like to hear @kajiglet and/or @dharhas opinions on this

**Comment by philippjfr** [comment]
>The results appear to be one big array of points, each line separated by a NaN point. Is that correct?

That is correct, I'd probably suggest using ``dashboard.result.split(datatype='array')`` and ``dashboard.result.geom()`` instead though.

>Other software handles this by returning polygons, grabbing the image edges as needed.

I'll try to find an implementation that generates closed polygons from the contours.

>The minimum threshold is handled by pixel (i think) area of the returned polygons.

That might be easiest.

>Depending on how things come back from GrabCuts, that may not be appropriate (would I ever get a path that for some reason was broken into three conjoined pieces, with say, one short piece in the middle?).

The OpenCV grabcut implementation returns 2D mask which labels each pixel as either belonging to the foreground or background. Currently we extract contours from this using matplotlib's contours operation, I could turn those closed paths (i.e. polygons) easily enough. That seems like the most straightforward solution anyway.

**Comment by kajiglet** [comment]
I would prefer the default tool for denoting the foreground and background to be line based. Its easier to click out a polyline down the middle of a coastal inlet and river when zoomed out (but can still see the water features). Line width relative to image pixel size is important as visual appearance of the line and the interpretation of which pixels image pixels the line is marking varies with the zoom level. Being able to switch to a polygon will be beneficial in some cases, but I feel users will tend to over-specify and focus too much on details.

Generating closed polygons from the contours as the result is preferred.

**Comment by kcpevey** [comment]
Also note that freehand drawing is a milestone which, as a user, would be even easier to utilize for foreground/background specification. I think the way Philipp has it set up now will allow us to switch between the tools and set the default tool.

**Comment by philippjfr** [comment]
Another thing that was mentioned is adding drawing tools to the plot showing the computed contours so they too can be edited.

**Comment by kcpevey** [comment]
@jlstevens you might want to see if any of this can easily be taken care of while you're working on the grabcut dashboard.

**Comment by kcpevey** [comment]
I think most of what was discussed here has been address. I'm closing in favor of more direct issues with using the new panelized implementation
