### ISSUE TITLE
Add functionality to fetch tile source image from URL and bounding box

### ISSUE THREAD

**Issue by philippjfr** [pyviz/EarthSim#120]
In order to extract watersheds and coastlines for a particular region it would be very useful to provide an API to query a tile source URL for imagery of a particular region. As I understand it such an API is currently being built inside quest and could be exposed in EarthSim (ping @sdc50).

**Comment by philippjfr** [comment]
@sdc50 Is there a small example that I can play around with now? Once I've played with it a bit I can arrange a meeting with Aaron.

**Comment by sdc50** [comment]
@philippjfr Sorry for not responding sooner (@Aaron77 is trying to help me be more active on GitHub).  @Aaron77 just submitted a PR  (#174) with the notebook he demoed last week. He also just released a new version of Quest (2.6) which has his latest changes.

**Comment by kcpevey** [comment]
@philippjfr Does this still need to be set as blocked? The quest functionality is in place and the earthsim/grabcuts use is being worked on in https://github.com/pyviz/EarthSim/pull/186 by @jlstevens
