### ISSUE TITLE
Cell magic plot options - () vs []

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#127]
I'm sure I've asked this question before but... why are some of the plot options required to go into parentheses and some options required to go into brackets? I have in my notes: `[kdims]` and `(vdims)` but when I'm just trying to manipulate what my plot looks like, these don't seem to be relevant. Am I missing something?  

`%%opts Points (size=10, cmap=colors) [color_index='Max_Wind_Speed', color_levels=levels, colorbar=True] `

**Comment by philippjfr** [comment]
Plot options are denoted with square brackets (``[ ]``) and are things that HoloViews/GeoViews controls and usually control things about the axes or how the data is mapped to the plot type, style options on the other hand are denoted by parentheses (``( )``) and are things that control the visual styling of the plot and usually directly passed to the plotting backend (in this case bokeh).

**Comment by jbednar** [comment]
It's extremely important that we keep these types of options separate at the implementation level, but at the user level, in practice we've found that there is almost never any conflict between the categories, and so it's not particularly important that the user keeps the two categories straight.  Accordingly, the new `.options()` calls no longer require the user to specify the two types of options separately.  We have an open task to make the %%opts magic similarly not require that they be separated, which it sounds like you'd vote for!

**Comment by philippjfr** [comment]
Options are always applied per layer, this means that these two approaches are equivalent:

```python
hv.Points(...).options(size=20) * gv.Path(...).options(line_width=10)
```

```python
(hv.Points(...) * gv.Path(...)).options('Path', line_width=10).options('Points', size=20)
```

Certain options (usually plot options) apply to all kinds of elements and overlays though which means this can be valid:

```python
(hv.Points(...) * gv.Path(...)).options(width=600, height=400, xaxis=None)
```

Basically when you call ``.options()`` without specifying what the option should apply to it will apply it to the outermost object, which in this case is the ``Overlay`` of the Points and Path.
