### ISSUE TITLE
Address any remaining issues specifying extents

### ISSUE THREAD

**Issue by philippjfr** [pyviz/EarthSim#134]
In the old (private) repo an issue (https://github.com/ContinuumIO/EarthSim/issues/133) about setting extents on the Annotator classes was filed which wasn't transferred to this new repo. The issue involved requiring a user to override the default extent with NaNs. We should still address this.

**Comment by kcpevey** [comment]
This is still an issue. I have to initial annotators with `extent=(np.NaN,)*4`

**Comment by philippjfr** [comment]
I'm going to try finishing off the holoviews padding PR this weekend, which has been a prerequisite for removing this.

**Comment by philippjfr** [comment]
The PR was merged so I'll close now. Please reopen if encountering new issues.
