### ISSUE TITLE
GrabCuts dashboard

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#145]
It makes sense to me to load the poly editing tool(s) for the grabcuts results drawing (currently no tools are loaded).  
  
![grabcuts](https://user-images.githubusercontent.com/15659110/42517737-09fa6b38-8426-11e8-9038-b5d1e8def28e.PNG)

**Comment by philippjfr** [comment]
>It makes sense to me to load the poly editing tool(s) for the grabcuts results drawing

Agreed, I can add that.

>currently no tools are loaded

What do you mean? The plot on the left in your screenshot has two polygon draw tools.

**Comment by jbednar** [comment]
Sometimes we have a shared set of tools that apply to all plots, and other times they are separate as here, and it's hard to notice that there's another set that applies on the left.  It can be helpful to have separate tools so that only the ones relevant for each plot are shown, and so that different ones can be selected for each plot, but it's also more confusing in many cases.  Is there a way to choose whether we want separate or combined sets of tools?

**Comment by philippjfr** [comment]
>Is there a way to choose whether we want separate or combined sets of tools?

Yes using the ``merge_tools`` option, but in this case that is not an option. When you set ``merge_tools=True`` it also combines any duplicate tools which would be incorrect in this case since we want separate polygon draw tools for the foreground and background.

**Comment by kcpevey** [comment]
>currently no tools are loaded   
  
I just meant no polyEdit or polyDraw tools are loaded for the righthand figure  
  
The two sets (background and foreground for the left and a separate one for the right) make sense to me. What is a little confusing is the fact there is no visual boundary for the righthand figure. So one might be led to think that the tools in the center of the screen might be for both images since the righthand is empty (this is especially true if your figure is larger than the cell which I think is what Dharhas saw yesterday).   a
  
I think you guys are talking about two different things. @jbednar is talking about duplicating polyDraw on both the left and right figure and @philippjfr is talking about duplicating the polyDraw twice on the left figure for foreground and background.

**Comment by philippjfr** [comment]
>I just meant no polyEdit or polyDraw tools are loaded for the righthand figure

I see, yes, I hadn't thought about manually editing the contour once it has been computed but that seems like a sensible extension.

>What is a little confusing is the fact there is no visual boundary for the righthand figure. So one might be led to think that the tools in the center of the screen might be for both images since the righthand is empty

Yes, I see how that might be quite confusing. You think this might be improved by moving the toolbars to the top of the figure?

**Comment by jbednar** [comment]
> When you set merge_tools=True it also combines any duplicate tools which would be incorrect in this case since we want separate polygon draw tools for the foreground and background.

Sounds like we need a `merge_toolbars` option.

**Comment by philippjfr** [comment]
>Sounds like we need a merge_toolbars option, which merges the toolbars but doesn't merge duplicated tools.

This would require changes in bokeh as far as I'm aware.

**Comment by jbednar** [comment]
Yes, I'm sure; I just can't quite think through whether it's even a meaningful proposal for bokeh, i.e. whether it can be implemented in a general and reasonable way.

**Comment by philippjfr** [comment]
That is a good question and I think it might require some tool specific implementation, e.g. there is no good reason to have multiple pan or zoom tools but there are definitely good reasons to have separate draw tools.

**Comment by jbednar** [comment]
Ok, thanks.  I guess I'll file the issue on Bokeh but indicate that it's not high priority compared to the apparent complexity.

**Comment by jbednar** [comment]
https://github.com/bokeh/bokeh/issues/8074

**Comment by jbednar** [comment]
@kcpevey, Bryan indicates that it wouldn't be hard to allow `merge_tools` to be used in this case, preserving all copies of the drawing tools while merging all the simple pan and zoom tools: https://github.com/bokeh/bokeh/issues/8074#issuecomment-403892229

Let us know if you want us to add that to our to-do list.

**Comment by kcpevey** [comment]
@jbednar My initial thinking is that merging tools would complicate access to (and output from) `poly_table`.   
  
I'm leaning towards leaving them as separate tools, but I want to play with it a little more before I make a definitive decision.

**Comment by philippjfr** [comment]
In the latest bokeh releases drawing tools are no longer merged.
