### ISSUE TITLE
TriMesh polygon display

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#149]
I believe TriMesh displays on the drawing tools by drawing the individual triangles as polygons (edges, not datashading). Is that correct?  
  
How/where is that happening in the code?   
  
Or... are just the edgepaths draw as three separate lines? That would be more computationally efficient.

**Comment by philippjfr** [comment]
Could you clarify which example you're referring to here or is this just a general question? If you plot a TriMesh directly it will indeed be rendered as a collection of nan separated paths, which I'm fairly sure is about as efficient as it's going to get. You can see how the TriMesh gets expanded into a set of lines in the ``TriMesh.edgepaths`` property.

**Comment by kcpevey** [comment]
That answers my question. TriMesh is drawn by drawing each element as 3 lines, NOT a polygon.
