### ISSUE TITLE
FiligreeDashboard size constraint not working

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#150]
In Specifying_Meshes.ipynb in the FiligreeDashboard, when you add points to mesh and specify the 'size' via the table, and then `update_mesh`, the `size` doesn't appear to have an effect. I think that the update mesh function isn't reading the size from the table like it should.

**Comment by philippjfr** [comment]
Works fine when I try it, could this simply be related to https://github.com/pyviz/EarthSim/issues/29?

**Comment by kcpevey** [comment]
Yes, that's the issue. It works with a size of 2000.   
  
But this brings up a good point. I want that lat/lon in the table to be displayed in Plate Carree, but I want size to be displayed in Mercator or something cartesian.

**Comment by kcpevey** [comment]
Closing since this is an external package issue that is being addressed elsewhere.
