### ISSUE TITLE
TriMesh disappears if no boundary is visualized

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#176]
I have a TriMesh that looks good at 100% zoom of the notebook (note that in the SW corner there is a segment of the edge boundary showing):  
![trimesh_zoom1](https://user-images.githubusercontent.com/15659110/43737149-ec73d7c8-9985-11e8-8953-ae6eb0b6e749.PNG)
  
Without touching the drawing tools zoom, I simply `pan` over to the right such that the boundary segment that was in SW corner is now off the screen and the entire drawing is covered by the TriMesh:  
![trimesh_zoom2](https://user-images.githubusercontent.com/15659110/43737209-2799153e-9986-11e8-931f-387dfb76ec95.PNG)
  
The TriMesh seems to have disappeared and all I can see are some dots of varying resolution.  
  
May or may not be related to #23

**Comment by philippjfr** [comment]
I think this might be related to https://github.com/bokeh/datashader/issues/357 somehow.

**Comment by jbednar** [comment]
I agree; it could be caused by https://github.com/ioam/holoviews/pull/2923/files . I'm not sure what is making the background light blue, but I would suspect that if you changed its color you'd see the lines again, because the trimesh is probably being drawn with vertices in dark blue and lines in light blue.

**Comment by kcpevey** [comment]
The background is from a WMTS ('https://maps.wikimedia.org/osm-intl/{Z}/{X}/{Y}@2x.png'). I switched it to world imagery ('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}'). You guys are right. Here are the two images again with the world imagery WMTS:  
  
![trimesh_zoom1b](https://user-images.githubusercontent.com/15659110/43779740-b078fd40-9a1e-11e8-8fb4-93e4a89fbd82.PNG)
  
![trimesh_zoom2b](https://user-images.githubusercontent.com/15659110/43779751-b53097da-9a1e-11e8-930a-2a5181b9b8a1.PNG)
  
Note that this is happening for the TriMesh examples in Visualizing_Meshes.ipynb from the earthsim repo. However, its probably happening in other notebooks too since I think all the example notebooks use the wikimedia source.

**Comment by kcpevey** [comment]
Also - I don't want this color to change based on zoom level or amount of data present. For example, this is that same mesh zoomed out.   
  
![trimesh_zoom3b](https://user-images.githubusercontent.com/15659110/43780223-b98ad236-9a1f-11e8-9a33-a1213afa9122.PNG)
  
For a TriMesh, this doesn't make sense. It should always remain a constant color.

**Comment by philippjfr** [comment]
We should simply set the datashade aggregator to 'any', that should solve it.

**Comment by philippjfr** [comment]
I also maintain my argument that 'any' should be the default for paths (and trimesh edges), as @kcpevey it doesn't make sense here as hightlighting the overlap between the paths is imo irrelevant.

**Comment by jbednar** [comment]
I think `any` should be the default for trimesh edges; overlap between edges is indeed irrelevant.  And the same is true for any collection of boundaries or other notionally non-overlapping patterns.  But Path in its most direct interpretation, e.g. as a GPS track, seems like it should indicate overlap, to show hotspots.

**Comment by kcpevey** [comment]
So, I have a loose understanding of the way the aggregation works in datashader. It makes sense when I think about the `mean` aggregator. But now that I'm thinking about it...  
  
1. What does the aggregator `any` do?  
2. For TriMesh, it seems like a flag of `none` makes more sense, since I really don't want or care about aggregation.

**Comment by philippjfr** [comment]
>What does the aggregator any do?

'any' is simply boolean, i.e. is there or isn't there something inside the pixel.

>For TriMesh, it seems like a flag of none makes more sense, since I really don't want or care about aggregation.

'any' is basically that, I would still call that aggregation though.

**Comment by kcpevey** [comment]
`mean` takes the mean value of all the data in the pixel  
`any` flags each pixel as *ON* if any data is available in the pixel  
  
Right?

**Comment by philippjfr** [comment]
Right.
