### ISSUE TITLE
Update to latest holoviews and geoviews packages

### ISSUE THREAD

**Issue by ceball** [pyviz/EarthSim#18]
Instead of installing via pip.

holoviews 1.9.4 is available on ioam now (and I guess will be on conda-forge soon). We're working on a geoviews package.

**Comment by ceball** [comment]
Oops, I was mistaken about the contents of the recent hv release.

**Comment by jbednar** [comment]
Right; 1.9.4 is just a bugfix release and has no TriMesh support.  But we should be able to have a 1.10 dev release.

**Comment by jlstevens** [comment]
Version 1.10 is out now though there are a few issues (primarily holomap export) that will be fixed shortly in 1.10.1. For geoviews, the latest tag is v1.5.0a1 @philippjfr  I am happy to release geoviews now though maybe you would prefer to wait for 1.10.1?

Once the new geoviews is released, we can update it here.

**Comment by philippjfr** [comment]
Yes, let's wait for 1.10.1, I'd also like to finish off the updated GeoViews website.

**Comment by kcpevey** [comment]
@philippjfr  I know there are some new versions coming out in the next few days, but I wanted to make sure I updated to the current version of holoviews, geoviews, and bokeh before our call today. Unfortunately, that broke things. Now I'm getting an error on the import of geoviews.Polygon.   
  
I pulled holovews from /pyviz/label/dev and geoviews from ioam. Can you clarify what channels I should be getting these packages from?

**Comment by philippjfr** [comment]
You probably still need:

```
conda install -c ioam/label/dev geoviews
conda install -c ioam holoviews
```

**Comment by jbednar** [comment]
Closing this one in favor of #117.
