### ISSUE TITLE
Vector visualization in Visualizing_Meshes.ipynb example

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#19]
In cell 9, in the time_field def, the line   
`angle = np.arctan(vy/vx)`  
should be changed to   
`angle = np.arctan2(vy, vx)`  
Since we need to visualize vectors on all four quadrants. Otherwise, the visualization of the results is incorrect since its limited to [-90 90]

**Comment by philippjfr** [comment]
Yes, definite oversight on my part.

**Comment by kcpevey** [comment]
@philippjfr This should be a quick fix that might can be swept up into another PR. :)

**Comment by philippjfr** [comment]
Agreed, will do that shortly unless you want to.

**Comment by kcpevey** [comment]
done.

**Comment by philippjfr** [comment]
These changes have now been merged.
