### ISSUE TITLE
Quest conda package size

### ISSUE THREAD

**Issue by ceball** [pyviz/EarthSim#191]
@AaronV77, just wondering why the quest packages are so different in size for different python versions?

<img width="436" alt="screen shot 2018-08-17 at 2 13 02 pm" src="https://user-images.githubusercontent.com/1929/44267888-cb1e8780-a227-11e8-961e-799be4d8abe2.png">

(same kind of pattern on linux and mac)

Are there some stray files in `info/recipe/outputdir` in some of the packages?

```
$ ls info/recipe/outputdir/
linux-32	linux-aarch64	linux-armv7l	noarch		win-32
linux-64	linux-armv6l	linux-ppc64le	osx-64		win-64
$ du -sh info/recipe/outputdir/
 14M	info/recipe/outputdir/
```

**Comment by AaronV77** [comment]
@ceball huh, I never really paid attention to it honestly, but it does seem like it is only Quest that is doing this weird behavior. When I go to release the 2.6.1 version of Quest and see what is happening with the build and try to sort it out. I think I should be able to start building some time early next week. Thanks

**Comment by ceball** [comment]
No problem, I just happened to notice it. Can definitely wait until next time you are releasing quest for some other reason.

**Comment by philippjfr** [comment]
The recent quest noarch build is only 72 KB so I think this can be closed.
