### ISSUE TITLE
parambokeh unable to handle ObjectSelector without a specified default

### ISSUE THREAD

**Issue by sdc50** [pyviz/EarthSim#199]
If an `ObjectSelector` parameter is specified without a default value then `paramnb` is able to render it, but `parambokeh` throws an error:

![image](https://user-images.githubusercontent.com/6454472/44481589-d862ba00-a60b-11e8-9f10-de4131f84127.png)

**Comment by jbednar** [comment]
I think parambokeh should do the same as paramnb, i.e. to take the first item in the list.

**Comment by philippjfr** [comment]
We've now switched to ``panel`` which picks the first item in the list by default.
