### ISSUE TITLE
Is there a 'polyline' in the Drawing tools?

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#20]
I need to draw a multi-point line, is that possible with the drawing tools or do I need to adapt `PointDraw` and/or `PolyDraw`?

**Comment by philippjfr** [comment]
You can use a ``PolyDraw`` stream and attach it to a ``Path`` element like this:

```python
path = gv.Path([])
hv.streams.PolyDraw(source=path)
path
```

**Comment by kcpevey** [comment]
That exactly what I need for drawing, thanks.  
  
I'm trying to get the data back out of it and it doesn't seem to be populating with my drawn data. The output of `path` gives `PolyDraw(data={'xs': [], 'ys': []})` - path.data is empty. Using `source=path` should have linked the front and back ends, right? What am I missing?

**Comment by philippjfr** [comment]
The data will appear on the ``stream.data`` not the element, i.e. once you've run this:

```python
path = gv.Path([])
stream = hv.streams.PolyDraw(source=path)
path
```

and drawn something you can now access the data on ``stream.data`` or ``stream.element`` or ``stream.element.geom()``.

**Comment by kcpevey** [comment]
Got it, that works great. Thanks!
