### ISSUE TITLE
next_n argument doesn't work with parambokeh

### ISSUE THREAD

**Issue by sdc50** [pyviz/EarthSim#200]
Specifying the `next_n` argument when calling `parambokeh.Widgets` has no effect.

```
parambokeh.Widgets(parameterized_obj, next_n=1)
```

I would expect this to run the next cell when a parameter widget is updated but nothing happens.

**Comment by jlstevens** [comment]
Agreed. This sounds like a bug.

**Comment by jbednar** [comment]
I noticed that yesterday as well, but hadn't gotten around to filing a bug report.  Thanks for doing it for me!

**Comment by kcpevey** [comment]
yes! I ran across that a while back but I thought I just misunderstood what it was supposed to do. Always better to file a report I suppose.

**Comment by philippjfr** [comment]
My best guess is that parambokeh (or its future replacements) will never support the ``next_n`` option because the JS code that paramnb uses to make it work is exceptionally hacky.

**Comment by jbednar** [comment]
We should definitely make it not accept the option, then! :-)  In any case I think the recent Panel work will make it very unlikely that next_n would really be the best choice in any scenario.

**Comment by philippjfr** [comment]
Agreed, another problem with it is that even in paramnb it doesn't work in JupyterLab.

**Comment by jlstevens** [comment]
I also vote against `next_n` support due to how hacky it is to get working...
