### ISSUE TITLE
Annotating gv.Path

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#21]
Is it possible to annotate a Path stream?   
  
I'm looking at the GeoAnnotator class and it seems like in order to visualize anything along with the annotators, they need to passed in to the annotator class and the annotator class will construct it. That said, there is no mechanism there to add a path to my drawing (only points and polys). Is there some other workaround for this?

**Comment by philippjfr** [comment]
The ``GeoAnnotator`` classes were really meant as templates, which should be modified and/or expanded depending on a users needs. It should be very straightforward to add a parameter to the GeoAnnotator to switch between gv.Polygons and gv.Path.

**Comment by kcpevey** [comment]
That seems easier said than done, as least for me, but I'm making an attempt.     
  
Do you mention switching between gv.Polygons and gv.Path because BOTH cannot be drawn at the same time (i.e. you can't have two PolyDraw objects on one drawing)?

**Comment by philippjfr** [comment]
In the simple case you could just let a user switch between them by making the following changes/additions to ``GeoAnnotator``: 

```python
geometry_type = param.ClassSelector(default=gv.Polygons, class_=gv.Path)

def __init__(self, polys=None, points=None, **params):
        ...
        polys = [] if polys is None else polys
        points = [] if points is None else points
        self.polys = self.geometry_type(polys, crs=ccrs.GOOGLE_MERCATOR)
        ...
```
    
If you want to draw and annotate both polygons and paths a slightly more complex implementation would be needed.

**Comment by philippjfr** [comment]
Closed via https://github.com/pyviz/EarthSim/pull/46
