### ISSUE TITLE
Accessing `poly_columns` data

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#210]
Adding columns to the annotators adds the columns as vdims on the `polys`, but once the annotator is rendered, that is just trash data and we access the visualized/drawn objects via `poly_stream`. However, `poly_columns` never gets propagated to `poly_stream`. I don't see a way to access the values in the `poly_column`. 

```
annot = PolyAndPointAnnotator(
    poly_columns =['Group'], polys=[sample_poly], vertex_columns=['Weight'], 
    point_columns=['Size'],  points=sample_points)
```
  
`annot.poly_stream`   - doesn't include the poly_columns. How can I get that data?

**Comment by philippjfr** [comment]
Last I checked ``annot.poly_stream`` did include the ``poly_columns`` data, so there must have been a regression somewhere.

**Comment by philippjfr** [comment]
I can't seem to reproduce this issue, what exactly does the ``annot.poly_stream`` data look like? When I try it includes the 'Group' column specified in the ``poly_columns``:

```python
{'Group': ['A', 'B'],
 'xs': [[-10114986,
   -10123905.999999998,
   -10130333,
   -10121522,
   -10129889,
   -10122958.999999998],
  [-10111105.267007079, -10102191.208754042, -10105177.281855093]],
 'ys': [[3806789.9999999967,
   3812412.999999998,
   3807529.999999997,
   3805406.999999996,
   3798393.999999998,
   3796692.9999999995],
  [3803528.0636803433, 3812371.3717693132, 3795548.092560737]]}
```

**Comment by kcpevey** [comment]
```
annot.poly_stream
PolyDraw(data={'Longitude': [array([-10114986., -10123906., -10130333., -10121522., -10129889.,
       -10122959.])], 'Latitude': [array([3806790., 3812413., 3807530., 3805407., 3798394., 3796693.])]})
```
I updated all my pyviz-related packages yesterday. Its possible I missed something.

**Comment by philippjfr** [comment]
Could you report your holoviews and geoviews versions?

**Comment by philippjfr** [comment]
Oh also, is this before or after displaying the plot? I suspect the data won't be populated until the plot has been displayed.
