### ISSUE TITLE
param.Action broken?

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#211]
https://github.com/ioam/parambokeh/issues/9

**Comment by ahines** [comment]
Ok, so this was initially user error on my end. I am now able to recreate the ability to call a lambda function to append data to an array. However, now I'm not sure how to proceed. I would like to be able to call an external function when the button is clicked. Are there any examples of this?

**Comment by philippjfr** [comment]
param.Action definitely now works with ``panel``.
