### ISSUE TITLE
vertex_table breaks with shared_datasource=True

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#212]
Specifying `shared_datasource=True` causes the vertex table to never populate anything.   
  
I also can't seem to select any poly with `shared_datasource=True`. My understanding was that this would combine multiple tools into one, but maybe that's not what it actually does?

**Comment by philippjfr** [comment]
There should be no reason to use ``shared_datasource`` now, instead we've started using the ``DataLink`` class which does the same thing in a much more explicit way.

>My understanding was that this would combine multiple tools into one

Datasources are unrelated to tools so I suspect you are looking for a different option. What exactly are you trying to achieve, i.e. what tools do you want to combine?

**Comment by kcpevey** [comment]
I'm updating some older code so that makes sense. I just never removed it from my workflows. I looked back through the earthsim/examples and didn't see it being used anywhere so we're all good.

**Comment by philippjfr** [comment]
Great, thanks for double checking.
