### ISSUE TITLE
Using datetime objects as vdims in gv.Path

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#214]
Is that possible? Or do all vdims need to be floats?

**Comment by philippjfr** [comment]
>Is that possible? Or do all vdims need to be floats?

Should be possible but I'm not sure what the implications and use cases are. Do you want to color by the value or do something else with it?

**Comment by kcpevey** [comment]
This may have been effected by the fix in https://github.com/ioam/holoviews/pull/2990 . I'm not seeing this error anymore so I'm attaching a new snippet and screen grab. Now, I can add the 'Datetime' column to my point_columns. However, it doesn't display correctly in the `point_column`. Interestingly enough, it DOES display correctly if I pull the data back out the stream and display as a dframe.  
  
![datetime_column](https://user-images.githubusercontent.com/15659110/45236588-da7e7700-b2a1-11e8-93b5-3d0aef645f59.PNG)
  
```
data_df = pd.read_csv('../../data/hurricane_path_color.txt', delimiter=',', header=0, parse_dates=['Datetime'])
gvpath = gv.Path([data_df], kdims=['Longitude', 'Latitude'], vdims=['Datetime','Pressure','Max_Wind_Speed','Radius','Direction_Degrees','Direction_Speed'], crs=proj)
gvpoint = gv.Points(data_df, kdims=['Longitude', 'Latitude'], vdims=['Datetime','Pressure','Max_Wind_Speed','Radius','Direction_Degrees','Direction_Speed'], crs=proj)
annot = PolyAndPointAnnotator(path_type=Path, polys=gvpath, points=gvpoint,
                              point_columns=['Pressure','Max_Wind_Speed'],
                              tile_url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}',
                              crs=proj)

(annot.tiles * annot.polys * annot.points + annot.point_table).cols(1) 
```

**Comment by kcpevey** [comment]
And one more bit of weirdness... If I modify the Max_Wind_Speed in `point_table`, then the Datetime type switches from a `datetime` object to `int64`.   
  
![point_columns2](https://user-images.githubusercontent.com/15659110/45236908-db63d880-b2a2-11e8-8417-72067313be6c.PNG)

**Comment by philippjfr** [comment]
Will be fixed in https://github.com/ioam/holoviews/pull/3005

**Comment by philippjfr** [comment]
There are now new holoviews and geoviews alpha releases with the fix.
