### ISSUE TITLE
Combined panel.Column with panel.Tabs

### ISSUE THREAD

**Issue by Kniles77** [pyviz/EarthSim#215]
Is it possible to combined panel.Column with panel.Tabs by having Tab inside of Column.

**Comment by kcpevey** [comment]
following

**Comment by philippjfr** [comment]
That should absolutely be possible, have you run into any issues with this? This will be much easier to discuss with a concrete example.

**Comment by kcpevey** [comment]
@Kniles77 Can you come up with a concise example for this?
