### ISSUE TITLE
Date Picker is not editable in Panel

### ISSUE THREAD

**Issue by Kniles77** [pyviz/EarthSim#216]
Panels date-picker is behaving similar to the number issue raised earlier.

![screen shot 2018-09-06 at 10 56 06 am](https://user-images.githubusercontent.com/31943817/45169637-a92f7980-b1c3-11e8-8227-4c72fa569add.png)

**Comment by kcpevey** [comment]
i.e. the date picker widget inside of Panel is not showing up as editable (well, the widget doesn't show up at all as you can see above).

**Comment by kcpevey** [comment]
It is now editable, but only as a text box/string. Was that the goal?  
![date](https://user-images.githubusercontent.com/15659110/45889275-a1580380-bd85-11e8-9ac0-f13590f86bb5.PNG)
  
It is still not editable (the top widget shows how it says (invalid) upon editing. Related: https://github.com/pyviz/panel/issues/34

**Comment by philippjfr** [comment]
This is indeed a bug, what would you find more useful? Should it switch back to a ``DatePicker`` or should I fix the text box to parse the dates correctly?

**Comment by philippjfr** [comment]
The `DatetimeInput` widget was merged in https://github.com/pyviz/panel/pull/58

**Comment by sdc50** [comment]
I don't know how much work this would entail, but I think it would be nice to have a date/time picker widget similar to this: https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by kcpevey** [comment]
What we have is working now. I like the bootstrap version @sdc50 mentioned, but I think we'll consider that as a future enhancement.
