### ISSUE TITLE
Deleting freehand drawing paths

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#218]
How would one delete a freehand drawing path? For example, I just drew a path, realized its not were I want it, now I want to delete it.

**Comment by philippjfr** [comment]
You should be able to tap on an existing line with the tool and then press delete.

**Comment by kcpevey** [comment]
Ha. That definitely works.   
  
If you're using the grabcuts dashboard, you have to make sure you have the CORRECT freehand drawing tool selected :)

**Comment by philippjfr** [comment]
>If you're using the grabcuts dashboard, you have to make sure you have the CORRECT freehand drawing tool selected :)

That certainly makes things difficult, I'm working on making tools distinguishable as soon as I'm back on Wednesday.
