### ISSUE TITLE
datashader vs holoviews.operation.datashader

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#219]
Seems like I shouldn't need both of these, but they are both imported/used in the examples/Visualizing_Meshes.ipynb. Is that right?

**Comment by jbednar** [comment]
```
import datashader as ds
from holoviews.operation.datashader import datashade, rasterize
```

Here `datashade` (no 'r') is a HoloViews operation, applied to HoloViews elements.  `datashader` is the underlying library, abbreviated `ds` here.  Both are needed, because not everything from Datashader has been imported into HoloViews.
