### ISSUE TITLE
Modifying drawing via dynamic table - bug

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#22]
In the Annotators.ipynb on the PointAndPolyAnnotator drawing, if you create a point on the map and then go to the dynamic table below and edit the location of that point, the point disappears from the map (at least I can't find it - even after moving it 1 meter) but remains in the table. This looks like a bug.

**Comment by philippjfr** [comment]
This has been fixed by the latest HoloViews release. The problem was that the table changed the values from floats to strings, which no longer occurs.
