### ISSUE TITLE
PolyEdit tool missing from the poly annotators

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#222]
There is no `PolyEdit` tool with the `PolyAndPointAnnotator`. It looks like I *should* always get this since it's in the `GeoAnnotator` class. From the docs, it looks like this is happening with `PolyAnnotator` as well. Is that a bug?   
  
http://earthsim.pyviz.org/user_guide/Annotators.html

**Comment by philippjfr** [comment]
Looks like it, fixing that now.
