### ISSUE TITLE
PolyAndPointAnnotator not populating poly_stream correctly

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#225]
Given this:  

```
coord_system = ccrs.UTM(17)
display_extent = (-95, 25, -55, 50)
annot = PolyAndPointAnnotator(polys=[], path_type=gv.Path, crs=coord_system, extent=display_extent)
(annot.tiles * annot.polys * annot.points + annot.point_table + annot.vertex_table).cols(1)
```
  
When I draw paths, they don't appear in the `point_table`.   
  
The same thing happens with  

```
annot = PolyAndPointAnnotator(
    path_type=gv.Path, polys=[])
(annot.tiles * annot.polys * annot.points + annot.point_table + annot.vertex_table).cols(1)
```

but using `annot.view()` works correctly.

**Comment by kcpevey** [comment]
> When I draw paths, they don't appear in the point_table.   
  
Not entirely sure where my head was at when I wrote that. There doesn't appear to be an issue when I use `annot.poly_table` to visualize the *polys* table.   
  
At any rate, I still have an issue. Which is to say that if I draw a `path` on this drawing: 

```
coord_system = ccrs.UTM(17)
display_extent = (-95, 25, -55, 50)
annot = PolyAndPointAnnotator(polys=[], path_type=gv.Path, crs=coord_system, extent=display_extent)
(annot.tiles * annot.polys * annot.points + annot.poly_table + annot.vertex_table).cols(1)
```

the `annot.poly_stream` remains empty.   
  
```
annot.poly_stream  
PolyDraw(data={'Group': [], 'xs': [], 'ys': []})  
```  

However, the `annot.poly_stream` populates correctly with this:  
```
annot = PolyAndPointAnnotator(
    path_type=gv.Path, polys=[])
(annot.tiles * annot.polys * annot.points + annot.point_table + annot.vertex_table).cols(1)
```

**Comment by kcpevey** [comment]
@philippjfr Can you weigh in on this?

**Comment by philippjfr** [comment]
I can't reproduce any issues with the example unfortunately.

**Comment by kcpevey** [comment]
My hv was the same as yours, but my gv was slightly behind. Updated and now everything works like it should!
