### ISSUE TITLE
Installation errors on Windows10

### ISSUE THREAD

**Issue by markanthonycowan** [pyviz/EarthSim#227]
(C:\Users\rditlmac\AppData\Local\Continuum\Anaconda2\envs\python3) C:\Users\rditlmac\Downloads\earthsim>conda create -n earthsim -c conda-forge --file=dependencies.txt conda-forge::python=3.6
Fetching package metadata ...........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Packages missing in current win-64 channels:
  - conda-forge::fiona 1.7.12
  - pyviz/label/earthsim::gdal 2.2.4
  - conda-forge::cartopy 0.16.0
  - conda-forge::xarray 0.10.7
  - conda-forge::geopandas 0.3.0
  - conda-forge::jupyter 1.0.0
  - conda-forge::notebook 5.5.0
  - conda-forge::opencv 3.4.1
  - conda-forge::gsshapy 2.3.8
  - pyviz/label/earthsim::bokeh 1.0.0dev5
  - pyviz/label/earthsim::gssha 7.12+pyviz.0
  - pyviz/label/earthsim::filigree 0.2.2+pyviz.0
  - erdc::quest 2.6.1
  - pyviz/label/earthsim::datashader 0.6.7
  - pyviz/label/earthsim::param 1.7.0
  - pyviz/label/earthsim::parambokeh 0.2.3
  - pyviz/label/earthsim::paramnb 2.0.4
  - pyviz/label/earthsim::pyct 0.4.4a10
  - pyviz/label/earthsim::holoviews 1.11.0a4
  - pyviz/label/earthsim::geoviews 1.5.4a6
  - conda-forge::lancet 0.9.0
  - conda-forge::colorcet 1.0.0
  - conda-forge::scikit-image 0.14.0
  - conda-forge::descartes 1.1.0
  - conda-forge::nodejs 9.11.1
  - conda-forge::boost-cpp 1.66.0
  - pyviz/label/earthsim::libgdal
  - pyviz/label/earthsim::x264
  - pyviz/label/earthsim::zeromq
  - pyviz/label/earthsim::libkml
  - conda-forge::numpy 1.14.5
  - pyviz/label/earthsim::scipy 1.1.0
  - conda-forge::pytest
  - conda-forge::pyflakes
  - pyviz/label/earthsim::nbsmoke
  - conda-forge::python 3.6*

Close matches found; did you mean one of these?

    conda-forge::cartopy: conda-forge-ci-setup
    conda-forge::fiona: conda-forge-pinning
    conda-forge::lancet: conda-forge-ci-setup

You can search for packages on anaconda.org with

    anaconda search -t conda pyviz/label/earthsim::zeromq

(and similarly for the other packages)

**Comment by ceball** [comment]
Please could you supply the output of `conda info`?

**Comment by markanthonycowan** [comment]
(C:\Users\rditlmac\AppData\Local\Continuum\Anaconda2\envs\python3) C:\Users\rditlmac\Downloads\es-workflows-modularize_downloaded09142018\es-workflows-modularize>conda info
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\rditlmac\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\rditlmac\AppData\Local\Continuum\Anaconda2\envs\python3
       envs directories : C:\Users\rditlmac\AppData\Local\Continuum\Anaconda2\envs
          package cache : C:\Users\rditlmac\AppData\Local\Continuum\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

**Comment by kcpevey** [comment]
I successfully built the env on my windows machine with conda 4.5.6.
