### ISSUE TITLE
Deleting drawn paths or polygons leaves empty list in stream.data

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#25]
Completely deleting a path or polygon will leave an empty list in the Latitude/Longitude data list from the stream. The empty list will persist even when more polygons are added (i.e. the next new polygon doesn't fill the empty list).   
  
This isn't detrimental, just slightly annoying. Perhaps it shouldn't be happening in the first place?

**Comment by philippjfr** [comment]
>Completely deleting a path or polygon will leave an empty list in the Latitude/Longitude data list from the stream. The empty list will persist even when more polygons are added (i.e. the next new polygon doesn't fill the empty list).

Definitely shouldn't be happening as it has potential to confuse the code in other places.

**Comment by philippjfr** [comment]
I believe this was fixed by https://github.com/pyviz/EarthSim/pull/93, I no longer see empty lists appearing.
