### ISSUE TITLE
Grabcut missing a drawing tool

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#266]
The `GrabCutPanel` only has one freehand drawing tool but it needs to have two

**Comment by philippjfr** [comment]
I can't replicate this, it has two in my version. What version of bokeh do you have installed?

**Comment by kcpevey** [comment]
Good call. I updated all my pyviz stuff to master, but I forgot about Bokeh (using /pyviz/label/dev). Nice catch.
