### ISSUE TITLE
Plot options syntax

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#278]
`grabcut.py` has the following snippet of plot options:  
  
> options = Store.options('bokeh')
options.Points = Options('plot', padding=0.1)
options.Path = Options('plot', padding=0.1)
options.Polygons = Options('plot', padding=0.1)
  
These are a little different syntax than what's shown in the hv docs. Would this syntax still be recommended?  
  
I'd prefer to use it since the hv doc approach leaves me loading bokeh twice (once in the py file, once in the notebook), but I don't want to use a deprecated syntax.

**Comment by philippjfr** [comment]
>These are a little different syntax than what's shown in the hv docs. Would this syntax still be recommended?

This will continue to be supported  but I would not recommend it.

>I'd prefer to use it since the hv doc approach leaves me loading bokeh twice (once in the py file, once in the notebook), but I don't want to use a deprecated syntax.

Rather than loading the extension twice I'd probably just set the backend directly, e.g. the code above could be replaced with:

```python
hv.Store.set_current_backend('bokeh')
opts.defaults(
    opts.Points(padding=0.1),
    opts.Path(padding=0.1),
    opts.Polygons(padding=0.1))
```

**Comment by kcpevey** [comment]
Perfect. That's what I was looking for. Thanks!
