### ISSUE TITLE
Analyzing_meshes.ipynb - animation controls

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#32]
The slider controls for animations/time varying mapping are not working correctly. Specifically, once you start playing an animation, the slider quickly spins through several loops while the image slowly changes from one to another. There seems to be a significant delay in the movement of the slider and the changing of the image. If I tell it to loop, let the slider move through two loops, then click stop, it will slowly play through all the images in the two loops instead of stopping immediately. Does that make sense? It basically has the feel of being unresponsive to my stop click.   
  
Is this related to the dataset size or is there a time delay mismatch between the animation and the slider?

**Comment by philippjfr** [comment]
>Does that make sense? It basically has the feel of being unresponsive to my stop click.

I think it must be queuing too many events, which start accumulating Python side. The best workaround for now is to reduce the default update speed by lowering the fps setting, e.g.:

``%output fps=2``

I'll raise an issue in HoloViews to improve event throttling for the scrubber widget.

**Comment by kcpevey** [comment]
Ok yeah that fixes it. I know I've specified that %output in other notebooks so that explains why I didn't see it before. Thanks!

**Comment by philippjfr** [comment]
Raised this issue in holoviews, closing.
