### ISSUE TITLE
Reproject points mid-stream

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#33]
Is it possible to reproject the points such that the dynamic table of annotations "automatically" does the conversion between PlateCaree and Mercator? Basically, I want the displayed table to be in geographic lat/long. If conversion on the fly is possible, where would that sit?  
  
I'm working with the PointAnnotator right now, but it seems like I'd have to have an additional layer in which to put the conversion. I was thinking maybe something like inside of PolyAnnotator.load_table? I'll be honest... the poly annotator is completely confusing to me so I'm hesitant to head that direction without confirmation that 1) it can be done, 2) its a good idea, and 3) that's where it should sit

**Comment by kcpevey** [comment]
Can someone weigh in on this one?

**Comment by philippjfr** [comment]
>Is it possible to reproject the points such that the dynamic table of annotations "automatically" does the conversion between PlateCaree and Mercator? Basically, I want the displayed table to be in geographic lat/long. If conversion on the fly is possible, where would that sit?

We should be able to do this by adding separate lat/lon columns to the ``Table`` and hiding the actual underlying coordinate columns. I'll try to have a look at this today. As I mentioned in https://github.com/pyviz/EarthSim/issues/26, doing something similar for the ``PolyAnnotator`` should wait until we've found a good approach to share the data source between the polygon and table data.

**Comment by kcpevey** [comment]
Was this closed because it was resolved or was it closed until the poly annotator was updated? At any rate, I'm still interested in this functionality. @jbednar can you clarify?

**Comment by jbednar** [comment]
Can't recall, but it sounds like it should still be open.

**Comment by kcpevey** [comment]
To summarize anew: I want to visualize point_table, poly_table, and vertex_table in a crs of my choosing (at a minimum - NOT mercator).   
  
`Annotators.ipynb` provides good examples for testing.

**Comment by philippjfr** [comment]
>To summarize anew: I want to visualize point_table, poly_table, and vertex_table in a crs of my choosing (at a minimum - NOT mercator)

Once https://github.com/pyviz/EarthSim/pull/188 is merged all the tables should be in lat/lon. However since all the conversion happens on the frontend the displayed crs is not configurable.

**Comment by kcpevey** [comment]
I'm happy with the current state. Closing.
