### ISSUE TITLE
Switch all examples to use panel instead of parambokeh/paramnb

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#44]
Should I be using parambokeh or paramnb to display widgets? What's the difference?

**Comment by dharhas** [comment]
paramnb used jupyter notebook widgets to create the widgets. parambokeh uses bokeh widgets. One of the others can chime in on current status but a couple of months ago, paramnb had more widgets available but some were flaky/displayed oddly in annoying ways. parambokeh was under development with the plan to achieve feature parity to paramnb.

Also paramnb can only be used inside Jupyter while parambokeh can also potentially be used in standalone websites with a bit of work. So I think the general consensus is to use parambokeh unless there is a particular widget that is not available.

**Comment by jbednar** [comment]
That's correct.  As of the end of the previous project, I believe there was at least one widget not yet available in parambokeh that was being used in the example notebooks, so they had to use paramnb.  But it's on @ceball's list to eliminate that problem and then switch to parambokeh consistently.  I *think* the missing one was the file selector widget, but I may be misremembering that. Once he fixes that, we can consistently use the same package (parambokeh) and the same code whether or not we are in a Jupyter notebook.

**Comment by kcpevey** [comment]
And parambokeh can be used in a jupyter notebook too? What about JupyterLab?

**Comment by philippjfr** [comment]
>What about JupyterLab?

Not yet although that support is planned. JupyterLab have changed a lot of the infrastructure around communicating between the Python kernel and the JS frontend, an issue we've just solved for holoviews now by creating the ``jupyterlab_holoviews`` extension. We'd like to avoid requiring another extension, such as ``jupyterlab_parambokeh``, so we're still looking for good solutions.

**Comment by kcpevey** [comment]
The JupyterLab question is driven by my desire to use Anaconda Enterprise to deploy notebooks. JupyterLab compatibility would allow for easier creation of deployments, though it IS possible to view in Classic mode in AE. Once a notebook is deployed, I think its just running as Classic. That said, the deployments can't currently load widgets for some reason.   
  
All this to say our widget needs are also tied to our need to use them in AE deployments. The AE team is aware of that also. I'm not sure what needs to be done, but there may need to be some collaboration between the two.
