### ISSUE TITLE
Zoom single axes (unscaled) should be unavailable with projected data

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#45]
The wheel zoom functionality can be used to zoom a single axis. When one is displaying map data or projected data, its never appropriate to zoom a single axis. All zooming should be forced to the scaled zoom.

**Comment by kcpevey** [comment]
And now I think maybe I should never say never... how about it should default to disabled axis zoom?

**Comment by philippjfr** [comment]
This has long been an annoyance but as far as I'm aware there is no way to disable single axis zoom at the moment. Therefore this would have to be raised with bokeh before we could constrain it in GeoViews.

**Comment by kcpevey** [comment]
@philippjfr I raised an issue on Bokeh https://github.com/bokeh/bokeh/issues/7815 . You may be able to add more specific information.

**Comment by kcpevey** [comment]
I didn't realize this was addressed in https://github.com/bokeh/bokeh/pull/7743 . I had done a few searches but I've had my hands on so many things this afternoon, I somehow missed it.

**Comment by philippjfr** [comment]
This has now been merged into geoviews and should be enabled once bokeh 0.12.16 is released.
