### ISSUE TITLE
Quest broken

### ISSUE THREAD

**Issue by philippjfr** [pyviz/EarthSim#5]
As far as I can tell latest versions of quest are broken, when I try to request a feature from a USGS NLCD source it tries to make a request and then executes the following code from quest/services/usgs_nlcd.py, which results in a pandas KeyError:

```python
        r = requests.get(base_url, params=params)
        features = pd.DataFrame(r.json()['items'])
        features = features.loc[~features.title.str.contains('Imperv')]
        features = features.loc[~features.title.str.contains('by State')]
        features = features.loc[~features.title.str.contains('Tree Canopy')]
        features['geometry'] = features['spatial'].apply(_bbox2poly)
        features['download_url'] = features.webLinks.apply(_parse_links)
        #features['extract_from_zip'] = '.tif'
        features['filename'] = features['download_url'].str.split('FNAME=', expand=True)[1]
```

E                   KeyError: 1

@dharhas

**Comment by philippjfr** [comment]
Tried updating https://github.com/ContinuumIO/EarthSim-quest with the latest code on GitLab, there were some changes in the code so I'm hoping that will fix it.

**Comment by dharhas** [comment]
@philippjfr @sdc50 

There have been a bunch of changes to quest, including using params. We will look into fixing this.

**Comment by jbednar** [comment]
Can we roll back to a previous version for now?

**Comment by philippjfr** [comment]
It's the old version that was broken, I've now pushed the latest version from GitLab to the ContinuumIO/EarthSim-quest repo and apart from some perplexing issues with six this seems to be working now.
