### ISSUE TITLE
Current state of %%opts vs .options

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#50]
My cell magic opts for the polygon don't appear to be working/having any effect on my visualizations via the annotators. I believe we are moving away from cell magic %%opts and towards the `.options`, right? Have cell magics been phased out, is my `.options` specification overriding it, or is something else going on here?  
  
`%%opts Polygons (color='red' alpha=0.5 selection_alpha=0.8 nonselection_alpha=0.2) `  
  
`viz = PolyAndPointAnnotator(path_type=gv.Path, polys=[boundary_poly], 
                            crs=coord_sys,extent=(np.NaN,)*4) `   
`(viz.tiles * viz.polys * viz.poly_view.options(apply_ranges=False) * viz.points * datashade(trimesh.edgepaths) + viz.poly_table + viz.point_table).options(shared_datasource=True).cols(1)`

**Comment by philippjfr** [comment]
@kcpevey You are setting the options on ``Polygons`` in the magic but you've changed the element type to ``gv.Path``. Just change the line to:

```python
%%opts Path (color='red' alpha=0.5 selection_alpha=0.8 nonselection_alpha=0.2)
```

Magics will continue to be supported, ``.options`` is simply complementary and useful for generating code that works in and outside a notebook.

**Comment by kcpevey** [comment]
Got it. It was confusing that paths are handled with the polyAnnotator but they still remain paths.   
  
this can be closed.
