### ISSUE TITLE
%%opts warning with existing paths

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#51]
When I use the `%%opts` for Path, it throws a warning when I initialize my PolyAndPointAnnotator with an existing polygon and does not appear to be effective (it is not colored red). The warning is `WARNING: Unknown elements Paths not registered with any of the loaded backends.`    
  
```
%%opts Paths (color='red' alpha=0.5 selection_alpha=0.9 nonselection_alpha=0.6) 

viz = PolyAndPointAnnotator(path_type=gv.Path, polys=[boundary_poly], 
                            crs=coord_sys,extent=(np.NaN,)*4, tile_url='http://tile.stamen.com/terrain/{Z}/{X}/{Y}.jpg')

(viz.tiles * viz.polys * viz.poly_view.options(apply_ranges=False) * viz.points  +
                  viz.poly_table + viz.point_table).options(shared_datasource=True).cols(1)
```

**Comment by jbednar** [comment]
Path, not Paths.

**Comment by kcpevey** [comment]
My apologies for a simple mistake. This is more of a geoviews thing, but its awfully confusing for the elements not to be defined consistently as singular or plural:  
  
 `from geoviews import Polygons, Points, Path`

**Comment by jbednar** [comment]
Yes, that's very confusing, particularly since there are some non-Vectorized elements that truly are singular (HLine, VLine), and others that are used for multiple items (Path).  You should have *our* apologies. :-)
