### ISSUE TITLE
Visualizing data on TriMesh - colorbar and range

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#53]
I'm trying to read in a hotstart file (.hot) (formatted exactly the same as a result file (.dat)). I'm working off the same concepts in Visualizing_Meshes.ipynb. I can get it load in and plot. The TriMesh color contours appear to be linked to the ioh values like I want, but I can't get it `redim.range` and `colorbar=True` to have any effect. Here is the basic workflow:  
  
Read an AdH 3dm mesh and reproject the points  
```
tris, verts = read_3dm_mesh(fpath,skiprows=2)
points = gv.operation.project_points(gv.Points(verts, vdims=['z'], crs=coord_sys))
```
Add the hotstart data to the points (ioh) and plot  
```
%%opts TriMesh (cmap='RdYlBu') [color_index='ioh', colorbar=True]
fpath = os.path.join(path, filename + '.hot')
hotstart = read_mesh2d(fpath)
depth_points = points.add_dimension('ioh', 0, hotstart[0].values[:, 0], vdim=True)
hot_trimesh = gv.TriMesh((tris, depth_points))
viz.tiles * datashade(hot_trimesh, aggregator=ds.mean('ioh')).redim.range(ioh=(0, 6))
```
It looks like `aggregator=ds.mean('ioh')` is working correctly, but `.redim.range(ioh=(0,6)` has no effect.  I also have no colorbar.  
  
Also, there are no errors, but I am getting this warning: 
`C:\ProgramData\Anaconda3\envs\ers\lib\site-packages\IPython\core\interactiveshell.py:2903: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):`

**Comment by philippjfr** [comment]
@kcpevey The ``datashade`` operation colormaps the data and therefore converts it to an RGB image. Once converted to an RGB image no colorbar can be generated (easily), and the color range cannot be set. Instead use the ``rasterize`` operation, which you can import from ``holoviews.operation.datashader``, this applies the aggregation without the colormapping, returning an ``Image`` so you can do something like this:

```
%%opts Image (cmap='RdYlBu') [colorbar=True]
fpath = os.path.join(path, filename + '.hot')
hotstart = read_mesh2d(fpath)
depth_points = points.add_dimension('ioh', 0, hotstart[0].values[:, 0], vdim=True)
hot_trimesh = gv.TriMesh((tris, depth_points))
viz.tiles * rasterize(hot_trimesh, aggregator=ds.mean('ioh')).redim.range(ioh=(0, 6))
```
