### ISSUE TITLE
Update GSSHA workflows

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#55]
The GSSHA workflows need to be updated for the latest packages.  I ran into a variety of errors when I ran through them.   
  
I'm assigning this to myself as a back-burner task, but @dharhas or @kajiglet can feel free to direct it elsewhere.

**Comment by philippjfr** [comment]
>The GSSHA workflows need to be updated for the latest packages. I ran into a variety of errors when I ran through them.

To be clear, are you seeing regressions in the HoloViews/GeoViews/EarthSim code or in ``gsshapy``/``quest`` or one of the other ERDC maintained libraries?

**Comment by kcpevey** [comment]
I'm just looking into this, but at the moment, it looks like its going to be on ERDC's end. The first thing I ran into was the yml and `conda install -c conda-forge gsshapy` both chose to install `gsshapy=2.1.1` which is not compatible with the earthsim example notebooks. I had to pin the version number which updated and downgraded other packages:  
  
```
$ conda install -c conda-forge gsshapy=2.3.8
Solving environment: ...working... done

## Package Plan ##
  environment location: C:\ProgramData\Anaconda3\envs\ers
  added / updated specs:
    - gsshapy=2.3.8

The following NEW packages will be INSTALLED:
    gazar:      0.0.4-py35_0               conda-forge
    gsshapy:    2.3.8-py35_0               conda-forge
    pangaea:    0.0.4-py35_0               conda-forge
    utm:        0.4.2-py35_0               conda-forge
    wrapt:      1.10.11-py35_0             conda-forge
    wrf-python: 1.1.3-py35_0               conda-forge

The following packages will be UPDATED:
    numba:      0.37.0-np113py35h23266ec_0             --> 0.37.0-np114py35h6c8877a_0
    numpy:      1.13.3-py35h5c71026_4                  --> 1.14.2-py35h5c71026_1

The following packages will be DOWNGRADED:
    h5py:       2.7.1-py35_3               conda-forge --> 2.7.1-py35_2               conda-forge

Proceed ([y]/n)? y
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```
  
I'm not familiar enough with conda packaging to know why it didn't choose the more recent version. @dharhas might be able to address that from our end. Or maybe we just need to pin the yml?

**Comment by kcpevey** [comment]
Things to address in `GSSHA_Workflow.ipynb`:  
  
* [ ] `rm -r ./vicksburg_south/` not valid syntax via Windows ipynb  
* [ ] no *.ele data in the data folder (may not actually be required)  
* [ ] `ERROR:stevedore.extension:Could not load 'kitware-girder': No module named 'girder_client'`
* [ ] `ERROR:stevedore.extension:Could not load 'cuahsi-hydroshare': No module named 'hs_restclient'`  
* [ ] `INFO:rasterio._base:Failed to auto identify EPSG: 7` 
* [ ] Cannot draw because of projection issues (possibly related to the above). It is trying to use `_EPSGProjection(32615)`

**Comment by kajiglet** [comment]
The stevedore issues should be related to quest. I'll have Aaron Valoroso assist.
