### ISSUE TITLE
Reset button distorts image

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#59]
The first click of the reset button in the notebook drawing tools causes the original zoom level to be restored. Clicking the reset button when the drawing is at the original extents results in the image to be distorted (or is it a projection reversion?) and does not clear user inputs (but is it supposed to?).  
  
"Reset" is a vague term. There are actually several tasks that I see fitting into that category:   
Clear - remove all drawings from the image but keep zoom level (tiles only)    
Zoom extents -  zoom to the extents of the drawing/original extents    
Reset - return it to the original state in which it was drawn including zoom level, remove user drawn items (tiles and original data)

**Comment by philippjfr** [comment]
This is a longstanding annoyance that will require some changes in bokeh. We've never quite worked out how we could fix this but it will probably require some more general changes that will force bokeh to respect a specific aspect ratio.

**Comment by kcpevey** [comment]
> it will probably require some more general changes that will force bokeh to respect a specific aspect ratio.  
  
That may help/be useful in the issue with locking the single axis-zoom on projected drawings.

**Comment by philippjfr** [comment]
>That may help/be useful in the issue with locking the single axis-zoom on projected drawings.

This is now already implemented in geoviews master, although it may require a dev release of bokeh for now.
