### ISSUE TITLE
Inconsistent dict keys between original polys and user-drawn polys

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#60]
I'm using https://github.com/pyviz/EarthSim/pull/46 
From the annotators:
```
self.polys = self.path_type(polys, crs=crs)
self.poly_stream = PolyDraw(source=self.polys, data={})
```
  
I have a drawing where I bring in projected data via the annotators to be drawn with the initial load. My poly data is drawn in the proper geographic location. It is stored using `xs` and `ys` as keys in `poly_stream`:   
![poly_stream1](https://user-images.githubusercontent.com/15659110/39631134-fe4fc938-4f76-11e8-8657-2ca0ab2192a6.PNG)  
  
Now if I draw another poly on the map and reprint the poly_stream, you can see that it changed my dictionary keys to `Latitude` and `Longitude`.   
![poly_stream2](https://user-images.githubusercontent.com/15659110/39631327-7c02745c-4f77-11e8-94ee-cd784cfb4d5d.PNG)

**Comment by philippjfr** [comment]
This seems like a definite bug that should be raised in HoloViews, I'll create an issue there shortly.

**Comment by philippjfr** [comment]
Opened an issue upstream (see https://github.com/ioam/holoviews/issues/2650).

**Comment by philippjfr** [comment]
Now fixed upstream.
