### ISSUE TITLE
Need write mesh capability

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#63]
We currently have the capability to read an existing *.3dm mesh, create a new mesh using filigree and allow filigree to create a hard copy of the mesh, but we do not have the capability to write out a mesh via verts and tris variables.      
  
I'm not sure whether this would go in `earthsim/filigree.py` or `filigree` cli itself. I expect this is would be an ERDC task. Can @kajiglet or @dharhas give some direction?

**Comment by philippjfr** [comment]
It would be good to know if there is a more general, and well test 3dm file reader/writer out there. The utilities in EarthSim to read files are very barebones and almost certainly not very robust.

**Comment by dharhas** [comment]
This is a ERDC task. Filigree must already have a 3dm (or hdf5) writer embedded somewhere since the 3dm format was developed by Aquaveo. So we should talk with Aquaveo and wrap it into the filigree python wrapping project we will be starting shortly.

**Comment by kcpevey** [comment]
@dharhas filigree does have a 3dm writer in it. We just need to expose access to it via the python wrapper which shouldn't be too much work.
