### ISSUE TITLE
Roadmap: Task 1c: Parameterize notebook workflows

### ISSUE THREAD

**Issue by jlstevens** [pyviz/EarthSim#67]
Parameterize Jupyter-notebook workflows, to allow parameter sweeps to be automated and allow Jupyter notebooks to be used as components in larger workflows.

**Comment by jbednar** [comment]
Note I found from a few months back: As part of this work, should be able to collect notebook outputs into a per-run directory, to keep each run distinct (given that the EarthSim workflows typically aren't encapsulated within the notebook itself, so copying the notebook isn't sufficient to have a copy of that run). We've previously done similar things using [Lancet](http://ioam.github.io/lancet/).

**Comment by kcpevey** [comment]
Was this accomplished using Lancet 0.9.0? I know we got a demo, is there an example in the earthsim docs?
