### ISSUE TITLE
Annotating mesh edges for boundary conditions

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#7]
In order to create boundary conditions, I need access to the edges (or node numbers that make up the edges) of certain segments of a given mesh. This can be achieved either by:  
  
1) Creating a mesh, then interactively selecting and annotating certain edges of the existing mesh (through TriMesh? Is this possible?)  
or  
2) Annotating the polygon BEFORE meshing, then retaining the link between the original polygon and the resultant mesh edges. To do this with filigree, this will require some preprocessing scripts.

**Comment by jbednar** [comment]
Thanks for the issue!  I *thought* that's what you were up to, given your earlier question.  Option 2 seems like the right long-term solution, to avoid getting explicit user input bound together with a particular programmatically generated mesh.  I'm not sure how much work it is, though. @philippjfr?

**Comment by kcpevey** [comment]
Hydrodynamic modelers often need to modify the final mesh (nodal locations and elevations) so as a modeler, I'd prefer option 1, but I understand what you're saying and like we mentioned, CMB goes the option 2 route.   
  
All that said, is mesh modification on the back end going to be possible? Is that a goal?

**Comment by dharhas** [comment]
So option 2 was an original goal of the drawing tools even if it is not possible now I'd like to work out the path to making it happen. It might also need to wait until have a better wrapper on filigree that gives us bidirectional relationships between the polygon edges and the nodes. Or we might be able to fake that spatially matching the polygon edges with the nodes in python.

**Comment by kcpevey** [comment]
We've come a long way since this was opened. At this point, I think the path forward (ha), lies with Expansion of Path tool #38 . From there, I can apply other tools we now have available (interactive tables, annotators, widgets, etc) and see what needs arise.
