### ISSUE TITLE
Roadmap: Task 4b: Streamline use of Dask on HPC resources

### ISSUE THREAD

**Issue by jlstevens** [pyviz/EarthSim#76]
Streamline process of launching Dask on ERDC HPC Resources

**Comment by jbednar** [comment]
Dharhas has successfully demonstrated Dask on ERDC HPC systems using dask-jobqueue.  So far works well, but will bring up any rough edges when encountered.

**Comment by jbednar** [comment]
Seems like it's been working fine; closing.
