### ISSUE TITLE
Roadmap: Task 5c: Freehand drawing of regions

### ISSUE THREAD

**Issue by jlstevens** [pyviz/EarthSim#81]
Allow freehand drawing of regions

**Comment by kcpevey** [comment]
Is this to include freehand drawing of simple lines? That functionality would be useful in the GrabCuts implementation.

**Comment by jbednar** [comment]
I think we can quickly add something for this, but it's difficult to be sure it will be really usable for editing (a polyline, presumably, but with how many editable nodes, how to add editable nodes, etc.).

**Comment by jbednar** [comment]
Implemented in https://github.com/bokeh/bokeh/pull/8147
