### ISSUE TITLE
Latest quest causing raster-gdal error

### ISSUE THREAD

**Issue by philippjfr** [pyviz/EarthSim#91]
When running the tests currently we are getting a newer version of quest (quest-2.4.2.dev10), which seems to be causing error when reading rasters in the GSSHA notebooks. Specifically I'm seeing the following error:

```
E                   ~/build/pyviz/EarthSim/earthsim/gssha/__init__.py in get_file_from_quest(collection_name, service_uri, parameter, mask_shapefile, use_existing)
E                       118                                                    'service_uri': service_uri,
E                       119                                                    'parameter': parameter})
E                   --> 120     return quest.api.open_dataset(d).name
E                   
E                   ~/miniconda/envs/earthsim/lib/python3.6/site-packages/quest/api/datasets.py in open_dataset(dataset, fmt)
E                       388 
E                       389     if file_format not in list_plugins('io'):
E                   --> 390         raise ValueError('No reader available for: %s' % file_format)
E                       391 
E                       392     io = load_plugins('io', file_format)
E                   
E                   ValueError: No reader available for: raster-gdal
```

Our gdal dependencies have not changed at all, so I'm assuming this an issue with quest. @kcpevey @dharhas

**Comment by kcpevey** [comment]
Scott is working on new versions of the GSSHA notebooks because I was having some issues running them.

**Comment by dharhas** [comment]
So I got the new whitebox_tools (based on upstream) packaged and working on Thursday or Friday which was a prerequisite for getting the GSSHA workflow working again. It is on @sdc50 plate to start work on getting all working this week. Not sure how long it will take. 

I think it would totally reasonable to disable tests on these notebooks and re-enable them once we have the new versions working.

**Comment by AaronV77** [comment]
Alright this fix is simple and quick I believe, I figured out the problem and told Scott about it. Since I am not in the office until Wednesday there can be a quick PR for the simple change. Thanks.

**Comment by jlstevens** [comment]
Just a quick note to say that I got the 'GSSHA_Parameter_Sweep' notebook working by pinning quest to version 2.4.0:

![image](https://user-images.githubusercontent.com/890576/40360017-8e14302e-5dbc-11e8-95c2-8796b1814848.png)

```
pip install git+git://github.com/erdc/quest.git@2.4.0
```

**Comment by ceball** [comment]
We're using quest 2.4.1 in the current environment (just merged). Can anyone confirm that this issue doesn't apply to the current environment?

**Comment by AaronV77** [comment]
@ceball that issue is not present in that release of Quest but we did just release 2.5 for Quest.  Thanks.

**Comment by ceball** [comment]
Thanks. Do we need to update quest to 2.5 for any particular reason this week during scipy? If not, we should probably do it after.

**Comment by AaronV77** [comment]
@ceball there were major changes to how the infrastructure works, bug fixes, and new provider plugins were added. I would just use the release that you have and upgrade after SciPy. Thanks.

**Comment by ceball** [comment]
@AaronV77, I started upgrading to quest 2.5.0, but then I noticed there's no win64 quest package:

<img width="155" alt="screen shot 2018-07-17 at 10 54 32 am" src="https://user-images.githubusercontent.com/1929/42810449-d73f99c2-89af-11e8-9055-dc0cbb4b5dba.png">

(from https://anaconda.org/erdc/quest).

Is that deliberate, or an oversight? (Or am I looking in the wrong place?)

Thanks

**Comment by AaronV77** [comment]
@ceball I was just about to say something rhetorical until I saw the 2.4.1, yes that was an oversight on my part. The package has just been added to our Anaconda channel, sorry!
