### ISSUE TITLE
BoxEdit and PolyEdit/PolyDraw are incompatible in a single drawing

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#92]
If you use the BoxEdit and PolyDraw in drawings by themselves, the tool icon that shows up is different (a box or a polygon). However, when you try and put BOTH of these tools in the same drawing, strange things start happening. Here are some facts:  
1. The PolyDraw tools creates polygons, as expected, but when the polygon is finished with the double click, a box appears in addition to the polygon.  
2. Both the boxEdit icon and PolyDraw icon are available  
3. The BoxEdit icon works correctly  
4. The PolyEdit tool will select the polygons, but each new double-click for selection creates a NEW drawn box.   
  
![image](https://user-images.githubusercontent.com/15659110/40323310-9dae9af0-5cfa-11e8-85b2-fc8ce337db95.png)  
  
  
```
coord_sys = ccrs.UTM(15)

# load boundary polygon
bound_fname = os.path.join(workdir, 'boundary_poly.xyz')
bound_df = pd.read_csv(bound_fname, sep=' ', names=('x', 'y', 'z'))
bound_poly = list(zip(bound_df['x'], bound_df['y']))

box_poly = gv.Polygons([], crs=ccrs.GOOGLE_MERCATOR)
box_stream = BoxEdit(source=box_poly)

ann = PolyAndPointAnnotator(tile_url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}', 
                            extent=general_extent,
                            crs=coord_sys, polys=[bound_poly], points=[])

ann.tiles * ann.polys * ann.poly_view * ann.points * box_poly
```
Note: I'm using PR https://github.com/pyviz/EarthSim/pull/46

**Comment by philippjfr** [comment]
Thanks for the detailed bug report. This sounds like the BoxEditTool doubletap event isn't checking whether the tool is actually active before drawing. Should be an easy fix.

**Comment by philippjfr** [comment]
Fixed in https://github.com/bokeh/bokeh/pull/8076

**Comment by philippjfr** [comment]
Now merged, I'll update the env to use the latest bokeh dev build once that's been released.

**Comment by kcpevey** [comment]
@dharhas This is fixed

**Comment by philippjfr** [comment]
No bokeh dev build containing the fix yet afaik. I'll update once there is one.

**Comment by kcpevey** [comment]
Right, I guess "fixed" if you're working off of master which actually, I just realized I'm not because it requires complicated build...
