### ISSUE TITLE
Coordinate system specification causing empty poly_stream.element drawing

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#94]
```
coord_sys = ccrs.UTM(15)
ann = PolyAndPointAnnotator(tile_url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}', crs=coord_sys)  
ann.tiles * ann.polys * ann.poly_view * ann.points  
  
ann.poly_stream.element  
```

Specifying `coord_sys = ccrs.GOOGLE_MERCATOR` allows for the polygons to be redrawn with `ann.poly_stream.element`. However, `coord_sys = ccrs.UTM(15)`  causes `ann.poly_stream.element` to draw no polygons.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/geoviews/commit/ac371e127840ec8082faa084eff3e2dd740d7c9f
