### ISSUE TITLE
Is it possible to allow only one element per drawing?

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#96]
Is there a way to allow only ONE element of a given type in a drawing? For example, if I want to allow a user to draw a boundary box from which we will extract data, I only want ONE box to be allowed in the drawing. Drawing a second box should clear the first box. I'm looking for something similar for other things (only one path for dam line specification, only one point for reservoir location specification, etc). Is this possible?  
  
With multiples allowed, I'm just grabbing the first one drawn in my workflows, which is sub-optimal.

**Comment by philippjfr** [comment]
Added as part of https://github.com/bokeh/bokeh/issues/7987 and now merged.

**Comment by philippjfr** [comment]
Still needs to be exposed in HoloViews so I'll keep it open for now.

**Comment by jlstevens** [comment]
I believe the relevant HoloViews PR is now merged...
